version = ">= 1.7"

[giscus]
repo = "Rratic/p"
repo_id = "R_kgDOHtQy2g"
category = "General"
category_id = "DIC_kwDOHtQy2s4CTmdm"
mapping = "title"
lang = "zh-CN"

[pages]
lang = "zh"
logo_path = "assets/images/logo.png"
repo_name = "mine"
repo_owner = "Rratic"
server_prefix = "/mine"
title = "Rratic"
